// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  identityHex: __t.string(),
  sourceKey: __t.string(),
  title: __t.string(),
  body: __t.string(),
  coinReward: __t.u64(),
  crystalReward: __t.u32(),
  rubyReward: __t.u32(),
  emeraldReward: __t.u32(),
  itemRewardsJson: __t.string(),
};
