// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.5.0 (commit 19cbf2b219ac9fd7fdca6c5e2c61a3a2f0319515).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptTradeAllianceApplicationReducer from "./accept_trade_alliance_application_reducer";
import AdminDisbandTradeAllianceReducer from "./admin_disband_trade_alliance_reducer";
import AdminMergePlayerAccountsReducer from "./admin_merge_player_accounts_reducer";
import AdminMoveTradeAllianceMemberReducer from "./admin_move_trade_alliance_member_reducer";
import AdminSetTradeAllianceMemberRoleReducer from "./admin_set_trade_alliance_member_role_reducer";
import AnnounceLevelUpReducer from "./announce_level_up_reducer";
import AnnounceResearchReducer from "./announce_research_reducer";
import ApplyTradeAllianceReducer from "./apply_trade_alliance_reducer";
import BuyFromNpcReducer from "./buy_from_npc_reducer";
import BuyPlayerShopListingReducer from "./buy_player_shop_listing_reducer";
import CancelTradeAllianceApplicationReducer from "./cancel_trade_alliance_application_reducer";
import ClaimNpcMarketAdminReducer from "./claim_npc_market_admin_reducer";
import ClaimPlayerShopProceedsReducer from "./claim_player_shop_proceeds_reducer";
import ClaimTradeAllianceQuestRewardReducer from "./claim_trade_alliance_quest_reward_reducer";
import ClearPlayerShopSlotReducer from "./clear_player_shop_slot_reducer";
import CollectTradeAllianceRewardReducer from "./collect_trade_alliance_reward_reducer";
import CreateTradeAllianceReducer from "./create_trade_alliance_reducer";
import DiscoverPotionRecipeReducer from "./discover_potion_recipe_reducer";
import FillTradeAllianceItemQuestReducer from "./fill_trade_alliance_item_quest_reducer";
import JoinTradeAllianceReducer from "./join_trade_alliance_reducer";
import KickTradeAllianceMemberReducer from "./kick_trade_alliance_member_reducer";
import LeaveTradeAllianceReducer from "./leave_trade_alliance_reducer";
import MigratePlayerGameplaySavesReducer from "./migrate_player_gameplay_saves_reducer";
import RejectTradeAllianceApplicationReducer from "./reject_trade_alliance_application_reducer";
import RemoveNpcMarketItemConfigReducer from "./remove_npc_market_item_config_reducer";
import RemoveResearchConfigReducer from "./remove_research_config_reducer";
import ResetNpcMarketReducer from "./reset_npc_market_reducer";
import SellToNpcReducer from "./sell_to_npc_reducer";
import SendTradeAllianceChatMessageReducer from "./send_trade_alliance_chat_message_reducer";
import SendWorldChatMessageReducer from "./send_world_chat_message_reducer";
import SetAdminPlayerDataReducer from "./set_admin_player_data_reducer";
import SetMaintenanceModeReducer from "./set_maintenance_mode_reducer";
import SetNpcMarketItemBasePriceReducer from "./set_npc_market_item_base_price_reducer";
import SetPlayerGameplaySaveReducer from "./set_player_gameplay_save_reducer";
import SetPlayerLevelReducer from "./set_player_level_reducer";
import SetPlayerProfileReducer from "./set_player_profile_reducer";
import SetPlayerShopSlotReducer from "./set_player_shop_slot_reducer";
import SetTotalGeneratedGoldReducer from "./set_total_generated_gold_reducer";
import SetTradeAllianceMemberRoleReducer from "./set_trade_alliance_member_role_reducer";
import SetUsernameReducer from "./set_username_reducer";
import SubmitFeedbackReducer from "./submit_feedback_reducer";
import TickNpcMarketReducer from "./tick_npc_market_reducer";
import TransferTradeAllianceLeadershipReducer from "./transfer_trade_alliance_leadership_reducer";
import UpdateTradeAllianceProfileReducer from "./update_trade_alliance_profile_reducer";
import UpsertGameConfigReducer from "./upsert_game_config_reducer";
import UpsertNpcMarketItemConfigReducer from "./upsert_npc_market_item_config_reducer";
import UpsertResearchConfigReducer from "./upsert_research_config_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AdminPlayerFeedbackRow from "./admin_player_feedback_table";
import AdminPlayerGameplaySaveRow from "./admin_player_gameplay_save_table";
import GameConfigRow from "./game_config_table";
import GameConfigSnapshotRow from "./game_config_snapshot_table";
import LeaderboardRow from "./leaderboard_table";
import LeaderboardSummaryRow from "./leaderboard_summary_table";
import NpcMarketAdminRow from "./npc_market_admin_table";
import NpcMarketItemConfigRow from "./npc_market_item_config_table";
import NpcMarketPriceRow from "./npc_market_price_table";
import NpcMarketPriceSnapshotRow from "./npc_market_price_snapshot_table";
import OwnPlayerGameplaySaveRow from "./own_player_gameplay_save_table";
import OwnPlayerProfileRow from "./own_player_profile_table";
import OwnPlayerSessionRow from "./own_player_session_table";
import OwnPlayerShopListingRow from "./own_player_shop_listing_table";
import OwnPlayerShopProceedsRow from "./own_player_shop_proceeds_table";
import OwnPlayerShopTradeHistoryRow from "./own_player_shop_trade_history_table";
import OwnTradeAllianceChatRow from "./own_trade_alliance_chat_table";
import OwnTradeAllianceRewardInboxRow from "./own_trade_alliance_reward_inbox_table";
import PlayerRow from "./player_table";
import PlayerShopListingRow from "./player_shop_listing_table";
import PlayerShopProceedsRow from "./player_shop_proceeds_table";
import PlayerShopTradeRow from "./player_shop_trade_table";
import PlayerShopTradeRecentRow from "./player_shop_trade_recent_table";
import PotionRecipeDiscoveryRow from "./potion_recipe_discovery_table";
import PotionRecipeDiscoverySnapshotRow from "./potion_recipe_discovery_snapshot_table";
import PublicPlayerShopListingRow from "./public_player_shop_listing_table";
import ResearchConfigRow from "./research_config_table";
import ResearchConfigSnapshotRow from "./research_config_snapshot_table";
import TradeAllianceRow from "./trade_alliance_table";
import TradeAllianceApplicationRow from "./trade_alliance_application_table";
import TradeAllianceMemberRow from "./trade_alliance_member_table";
import TradeAllianceQuestContributionRow from "./trade_alliance_quest_contribution_table";
import TradeAllianceQuestProgressRow from "./trade_alliance_quest_progress_table";
import TradeAllianceApplicationSnapshotRow from "./trade_alliance_application_snapshot_table";
import TradeAllianceMemberSnapshotRow from "./trade_alliance_member_snapshot_table";
import TradeAllianceQuestContributionSnapshotRow from "./trade_alliance_quest_contribution_snapshot_table";
import TradeAllianceQuestProgressSnapshotRow from "./trade_alliance_quest_progress_snapshot_table";
import TradeAllianceSnapshotRow from "./trade_alliance_snapshot_table";
import WorldChatRow from "./world_chat_table";
import WorldChatRecentRow from "./world_chat_recent_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  gameConfig: __table({
    name: 'game_config',
    indexes: [
      { accessor: 'configKey', name: 'game_config_config_key_idx_btree', algorithm: 'btree', columns: [
        'configKey',
      ] },
      { accessor: 'byUpdatedAt', name: 'game_config_updated_at_idx_btree', algorithm: 'btree', columns: [
        'updatedAt',
      ] },
    ],
    constraints: [
      { name: 'game_config_config_key_key', constraint: 'unique', columns: ['configKey'] },
    ],
  }, GameConfigRow),
  leaderboard: __table({
    name: 'leaderboard',
    indexes: [
      { accessor: 'byDailyIncome', name: 'leaderboard_daily_income_idx_btree', algorithm: 'btree', columns: [
        'dailyIncome',
      ] },
      { accessor: 'identity', name: 'leaderboard_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'byMonthlyIncome', name: 'leaderboard_monthly_income_idx_btree', algorithm: 'btree', columns: [
        'monthlyIncome',
      ] },
      { accessor: 'byTotalIncome', name: 'leaderboard_total_income_idx_btree', algorithm: 'btree', columns: [
        'totalIncome',
      ] },
      { accessor: 'byWeeklyIncome', name: 'leaderboard_weekly_income_idx_btree', algorithm: 'btree', columns: [
        'weeklyIncome',
      ] },
    ],
    constraints: [
      { name: 'leaderboard_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, LeaderboardRow),
  npcMarketAdmin: __table({
    name: 'npc_market_admin',
    indexes: [
      { accessor: 'identity', name: 'npc_market_admin_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'npc_market_admin_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, NpcMarketAdminRow),
  npcMarketItemConfig: __table({
    name: 'npc_market_item_config',
    indexes: [
      { accessor: 'itemKey', name: 'npc_market_item_config_item_key_idx_btree', algorithm: 'btree', columns: [
        'itemKey',
      ] },
      { accessor: 'byUpdatedAt', name: 'npc_market_item_config_updated_at_idx_btree', algorithm: 'btree', columns: [
        'updatedAt',
      ] },
    ],
    constraints: [
      { name: 'npc_market_item_config_item_key_key', constraint: 'unique', columns: ['itemKey'] },
    ],
  }, NpcMarketItemConfigRow),
  npcMarketPrice: __table({
    name: 'npc_market_price',
    indexes: [
      { accessor: 'itemKey', name: 'npc_market_price_item_key_idx_btree', algorithm: 'btree', columns: [
        'itemKey',
      ] },
      { accessor: 'byItemKind', name: 'npc_market_price_item_kind_idx_btree', algorithm: 'btree', columns: [
        'itemKind',
      ] },
      { accessor: 'byUpdatedAt', name: 'npc_market_price_updated_at_idx_btree', algorithm: 'btree', columns: [
        'updatedAt',
      ] },
    ],
    constraints: [
      { name: 'npc_market_price_item_key_key', constraint: 'unique', columns: ['itemKey'] },
    ],
  }, NpcMarketPriceRow),
  player: __table({
    name: 'player',
    indexes: [
      { accessor: 'identity', name: 'player_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  playerShopListing: __table({
    name: 'player_shop_listing',
    indexes: [
      { accessor: 'listingKey', name: 'player_shop_listing_listing_key_idx_btree', algorithm: 'btree', columns: [
        'listingKey',
      ] },
      { accessor: 'byQuantity', name: 'player_shop_listing_quantity_idx_btree', algorithm: 'btree', columns: [
        'quantity',
      ] },
      { accessor: 'bySellerIdentity', name: 'player_shop_listing_seller_identity_idx_btree', algorithm: 'btree', columns: [
        'sellerIdentity',
      ] },
      { accessor: 'byUpdatedAt', name: 'player_shop_listing_updated_at_idx_btree', algorithm: 'btree', columns: [
        'updatedAt',
      ] },
    ],
    constraints: [
      { name: 'player_shop_listing_listing_key_key', constraint: 'unique', columns: ['listingKey'] },
    ],
  }, PlayerShopListingRow),
  playerShopProceeds: __table({
    name: 'player_shop_proceeds',
    indexes: [
      { accessor: 'sellerIdentity', name: 'player_shop_proceeds_seller_identity_idx_btree', algorithm: 'btree', columns: [
        'sellerIdentity',
      ] },
    ],
    constraints: [
      { name: 'player_shop_proceeds_seller_identity_key', constraint: 'unique', columns: ['sellerIdentity'] },
    ],
  }, PlayerShopProceedsRow),
  playerShopTrade: __table({
    name: 'player_shop_trade',
    indexes: [
      { accessor: 'byBuyerIdentity', name: 'player_shop_trade_buyer_identity_idx_btree', algorithm: 'btree', columns: [
        'buyerIdentity',
      ] },
      { accessor: 'bySellerIdentity', name: 'player_shop_trade_seller_identity_idx_btree', algorithm: 'btree', columns: [
        'sellerIdentity',
      ] },
      { accessor: 'tradeId', name: 'player_shop_trade_trade_id_idx_btree', algorithm: 'btree', columns: [
        'tradeId',
      ] },
      { accessor: 'byTradedAt', name: 'player_shop_trade_traded_at_idx_btree', algorithm: 'btree', columns: [
        'tradedAt',
      ] },
    ],
    constraints: [
      { name: 'player_shop_trade_trade_id_key', constraint: 'unique', columns: ['tradeId'] },
    ],
  }, PlayerShopTradeRow),
  potionRecipeDiscovery: __table({
    name: 'potion_recipe_discovery',
    indexes: [
      { accessor: 'byDiscoveredAt', name: 'potion_recipe_discovery_discovered_at_idx_btree', algorithm: 'btree', columns: [
        'discoveredAt',
      ] },
      { accessor: 'potionKey', name: 'potion_recipe_discovery_potion_key_idx_btree', algorithm: 'btree', columns: [
        'potionKey',
      ] },
    ],
    constraints: [
      { name: 'potion_recipe_discovery_potion_key_key', constraint: 'unique', columns: ['potionKey'] },
    ],
  }, PotionRecipeDiscoveryRow),
  researchConfig: __table({
    name: 'research_config',
    indexes: [
      { accessor: 'byGroupId', name: 'research_config_group_id_idx_btree', algorithm: 'btree', columns: [
        'groupId',
      ] },
      { accessor: 'researchId', name: 'research_config_research_id_idx_btree', algorithm: 'btree', columns: [
        'researchId',
      ] },
      { accessor: 'byUpdatedAt', name: 'research_config_updated_at_idx_btree', algorithm: 'btree', columns: [
        'updatedAt',
      ] },
    ],
    constraints: [
      { name: 'research_config_research_id_key', constraint: 'unique', columns: ['researchId'] },
    ],
  }, ResearchConfigRow),
  tradeAlliance: __table({
    name: 'trade_alliance',
    indexes: [
      { accessor: 'allianceId', name: 'trade_alliance_alliance_id_idx_btree', algorithm: 'btree', columns: [
        'allianceId',
      ] },
      { accessor: 'byMonthlyIncome', name: 'trade_alliance_monthly_income_idx_btree', algorithm: 'btree', columns: [
        'monthlyIncome',
      ] },
      { accessor: 'bySeasonIncome', name: 'trade_alliance_season_income_idx_btree', algorithm: 'btree', columns: [
        'seasonIncome',
      ] },
      { accessor: 'byTag', name: 'trade_alliance_tag_idx_btree', algorithm: 'btree', columns: [
        'tag',
      ] },
      { accessor: 'byTotalIncome', name: 'trade_alliance_total_income_idx_btree', algorithm: 'btree', columns: [
        'totalIncome',
      ] },
    ],
    constraints: [
      { name: 'trade_alliance_alliance_id_key', constraint: 'unique', columns: ['allianceId'] },
    ],
  }, TradeAllianceRow),
  tradeAllianceApplication: __table({
    name: 'trade_alliance_application',
    indexes: [
      { accessor: 'byAllianceId', name: 'trade_alliance_application_alliance_id_idx_btree', algorithm: 'btree', columns: [
        'allianceId',
      ] },
      { accessor: 'byApplicantIdentity', name: 'trade_alliance_application_applicant_identity_idx_btree', algorithm: 'btree', columns: [
        'applicantIdentity',
      ] },
      { accessor: 'applicationKey', name: 'trade_alliance_application_application_key_idx_btree', algorithm: 'btree', columns: [
        'applicationKey',
      ] },
      { accessor: 'byCreatedAt', name: 'trade_alliance_application_created_at_idx_btree', algorithm: 'btree', columns: [
        'createdAt',
      ] },
    ],
    constraints: [
      { name: 'trade_alliance_application_application_key_key', constraint: 'unique', columns: ['applicationKey'] },
    ],
  }, TradeAllianceApplicationRow),
  tradeAllianceMember: __table({
    name: 'trade_alliance_member',
    indexes: [
      { accessor: 'byAllianceId', name: 'trade_alliance_member_alliance_id_idx_btree', algorithm: 'btree', columns: [
        'allianceId',
      ] },
      { accessor: 'byJoinedAt', name: 'trade_alliance_member_joined_at_idx_btree', algorithm: 'btree', columns: [
        'joinedAt',
      ] },
      { accessor: 'memberIdentity', name: 'trade_alliance_member_member_identity_idx_btree', algorithm: 'btree', columns: [
        'memberIdentity',
      ] },
    ],
    constraints: [
      { name: 'trade_alliance_member_member_identity_key', constraint: 'unique', columns: ['memberIdentity'] },
    ],
  }, TradeAllianceMemberRow),
  tradeAllianceQuestContribution: __table({
    name: 'trade_alliance_quest_contribution',
    indexes: [
      { accessor: 'byAllianceId', name: 'trade_alliance_quest_contribution_alliance_id_idx_btree', algorithm: 'btree', columns: [
        'allianceId',
      ] },
      { accessor: 'contributionKey', name: 'trade_alliance_quest_contribution_contribution_key_idx_btree', algorithm: 'btree', columns: [
        'contributionKey',
      ] },
      { accessor: 'byContributorIdentity', name: 'trade_alliance_quest_contribution_contributor_identity_idx_btree', algorithm: 'btree', columns: [
        'contributorIdentity',
      ] },
    ],
    constraints: [
      { name: 'trade_alliance_quest_contribution_contribution_key_key', constraint: 'unique', columns: ['contributionKey'] },
    ],
  }, TradeAllianceQuestContributionRow),
  tradeAllianceQuestProgress: __table({
    name: 'trade_alliance_quest_progress',
    indexes: [
      { accessor: 'byAllianceId', name: 'trade_alliance_quest_progress_alliance_id_idx_btree', algorithm: 'btree', columns: [
        'allianceId',
      ] },
      { accessor: 'byDayKey', name: 'trade_alliance_quest_progress_day_key_idx_btree', algorithm: 'btree', columns: [
        'dayKey',
      ] },
      { accessor: 'questKey', name: 'trade_alliance_quest_progress_quest_key_idx_btree', algorithm: 'btree', columns: [
        'questKey',
      ] },
    ],
    constraints: [
      { name: 'trade_alliance_quest_progress_quest_key_key', constraint: 'unique', columns: ['questKey'] },
    ],
  }, TradeAllianceQuestProgressRow),
  worldChat: __table({
    name: 'world_chat',
    indexes: [
      { accessor: 'messageId', name: 'world_chat_message_id_idx_btree', algorithm: 'btree', columns: [
        'messageId',
      ] },
      { accessor: 'bySentAt', name: 'world_chat_sent_at_idx_btree', algorithm: 'btree', columns: [
        'sentAt',
      ] },
    ],
    constraints: [
      { name: 'world_chat_message_id_key', constraint: 'unique', columns: ['messageId'] },
    ],
  }, WorldChatRow),
  admin_player_feedback: __table({
    name: 'admin_player_feedback',
    indexes: [
    ],
    constraints: [
    ],
  }, AdminPlayerFeedbackRow),
  admin_player_gameplay_save: __table({
    name: 'admin_player_gameplay_save',
    indexes: [
    ],
    constraints: [
    ],
  }, AdminPlayerGameplaySaveRow),
  game_config_snapshot: __table({
    name: 'game_config_snapshot',
    indexes: [
    ],
    constraints: [
    ],
  }, GameConfigSnapshotRow),
  leaderboard_summary: __table({
    name: 'leaderboard_summary',
    indexes: [
    ],
    constraints: [
    ],
  }, LeaderboardSummaryRow),
  npc_market_price_snapshot: __table({
    name: 'npc_market_price_snapshot',
    indexes: [
    ],
    constraints: [
    ],
  }, NpcMarketPriceSnapshotRow),
  own_player_gameplay_save: __table({
    name: 'own_player_gameplay_save',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnPlayerGameplaySaveRow),
  own_player_profile: __table({
    name: 'own_player_profile',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnPlayerProfileRow),
  own_player_session: __table({
    name: 'own_player_session',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnPlayerSessionRow),
  own_player_shop_listing: __table({
    name: 'own_player_shop_listing',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnPlayerShopListingRow),
  own_player_shop_proceeds: __table({
    name: 'own_player_shop_proceeds',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnPlayerShopProceedsRow),
  own_player_shop_trade_history: __table({
    name: 'own_player_shop_trade_history',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnPlayerShopTradeHistoryRow),
  own_trade_alliance_chat: __table({
    name: 'own_trade_alliance_chat',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnTradeAllianceChatRow),
  own_trade_alliance_reward_inbox: __table({
    name: 'own_trade_alliance_reward_inbox',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnTradeAllianceRewardInboxRow),
  player_shop_trade_recent: __table({
    name: 'player_shop_trade_recent',
    indexes: [
    ],
    constraints: [
    ],
  }, PlayerShopTradeRecentRow),
  potion_recipe_discovery_snapshot: __table({
    name: 'potion_recipe_discovery_snapshot',
    indexes: [
    ],
    constraints: [
    ],
  }, PotionRecipeDiscoverySnapshotRow),
  public_player_shop_listing: __table({
    name: 'public_player_shop_listing',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicPlayerShopListingRow),
  research_config_snapshot: __table({
    name: 'research_config_snapshot',
    indexes: [
    ],
    constraints: [
    ],
  }, ResearchConfigSnapshotRow),
  trade_alliance_application_snapshot: __table({
    name: 'trade_alliance_application_snapshot',
    indexes: [
    ],
    constraints: [
    ],
  }, TradeAllianceApplicationSnapshotRow),
  trade_alliance_member_snapshot: __table({
    name: 'trade_alliance_member_snapshot',
    indexes: [
    ],
    constraints: [
    ],
  }, TradeAllianceMemberSnapshotRow),
  trade_alliance_quest_contribution_snapshot: __table({
    name: 'trade_alliance_quest_contribution_snapshot',
    indexes: [
    ],
    constraints: [
    ],
  }, TradeAllianceQuestContributionSnapshotRow),
  trade_alliance_quest_progress_snapshot: __table({
    name: 'trade_alliance_quest_progress_snapshot',
    indexes: [
    ],
    constraints: [
    ],
  }, TradeAllianceQuestProgressSnapshotRow),
  trade_alliance_snapshot: __table({
    name: 'trade_alliance_snapshot',
    indexes: [
    ],
    constraints: [
    ],
  }, TradeAllianceSnapshotRow),
  world_chat_recent: __table({
    name: 'world_chat_recent',
    indexes: [
    ],
    constraints: [
    ],
  }, WorldChatRecentRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_trade_alliance_application", AcceptTradeAllianceApplicationReducer),
  __reducerSchema("admin_disband_trade_alliance", AdminDisbandTradeAllianceReducer),
  __reducerSchema("admin_merge_player_accounts", AdminMergePlayerAccountsReducer),
  __reducerSchema("admin_move_trade_alliance_member", AdminMoveTradeAllianceMemberReducer),
  __reducerSchema("admin_set_trade_alliance_member_role", AdminSetTradeAllianceMemberRoleReducer),
  __reducerSchema("announce_level_up", AnnounceLevelUpReducer),
  __reducerSchema("announce_research", AnnounceResearchReducer),
  __reducerSchema("apply_trade_alliance", ApplyTradeAllianceReducer),
  __reducerSchema("buy_from_npc", BuyFromNpcReducer),
  __reducerSchema("buy_player_shop_listing", BuyPlayerShopListingReducer),
  __reducerSchema("cancel_trade_alliance_application", CancelTradeAllianceApplicationReducer),
  __reducerSchema("claim_npc_market_admin", ClaimNpcMarketAdminReducer),
  __reducerSchema("claim_player_shop_proceeds", ClaimPlayerShopProceedsReducer),
  __reducerSchema("claim_trade_alliance_quest_reward", ClaimTradeAllianceQuestRewardReducer),
  __reducerSchema("clear_player_shop_slot", ClearPlayerShopSlotReducer),
  __reducerSchema("collect_trade_alliance_reward", CollectTradeAllianceRewardReducer),
  __reducerSchema("create_trade_alliance", CreateTradeAllianceReducer),
  __reducerSchema("discover_potion_recipe", DiscoverPotionRecipeReducer),
  __reducerSchema("fill_trade_alliance_item_quest", FillTradeAllianceItemQuestReducer),
  __reducerSchema("join_trade_alliance", JoinTradeAllianceReducer),
  __reducerSchema("kick_trade_alliance_member", KickTradeAllianceMemberReducer),
  __reducerSchema("leave_trade_alliance", LeaveTradeAllianceReducer),
  __reducerSchema("migrate_player_gameplay_saves", MigratePlayerGameplaySavesReducer),
  __reducerSchema("reject_trade_alliance_application", RejectTradeAllianceApplicationReducer),
  __reducerSchema("remove_npc_market_item_config", RemoveNpcMarketItemConfigReducer),
  __reducerSchema("remove_research_config", RemoveResearchConfigReducer),
  __reducerSchema("reset_npc_market", ResetNpcMarketReducer),
  __reducerSchema("sell_to_npc", SellToNpcReducer),
  __reducerSchema("send_trade_alliance_chat_message", SendTradeAllianceChatMessageReducer),
  __reducerSchema("send_world_chat_message", SendWorldChatMessageReducer),
  __reducerSchema("set_admin_player_data", SetAdminPlayerDataReducer),
  __reducerSchema("set_maintenance_mode", SetMaintenanceModeReducer),
  __reducerSchema("set_npc_market_item_base_price", SetNpcMarketItemBasePriceReducer),
  __reducerSchema("set_player_gameplay_save", SetPlayerGameplaySaveReducer),
  __reducerSchema("set_player_level", SetPlayerLevelReducer),
  __reducerSchema("set_player_profile", SetPlayerProfileReducer),
  __reducerSchema("set_player_shop_slot", SetPlayerShopSlotReducer),
  __reducerSchema("set_total_generated_gold", SetTotalGeneratedGoldReducer),
  __reducerSchema("set_trade_alliance_member_role", SetTradeAllianceMemberRoleReducer),
  __reducerSchema("set_username", SetUsernameReducer),
  __reducerSchema("submit_feedback", SubmitFeedbackReducer),
  __reducerSchema("tick_npc_market", TickNpcMarketReducer),
  __reducerSchema("transfer_trade_alliance_leadership", TransferTradeAllianceLeadershipReducer),
  __reducerSchema("update_trade_alliance_profile", UpdateTradeAllianceProfileReducer),
  __reducerSchema("upsert_game_config", UpsertGameConfigReducer),
  __reducerSchema("upsert_npc_market_item_config", UpsertNpcMarketItemConfigReducer),
  __reducerSchema("upsert_research_config", UpsertResearchConfigReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.5.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

