// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  username: __t.string(),
  totalIncome: __t.u64().name("total_income"),
  dailyIncome: __t.u64().name("daily_income"),
  weeklyIncome: __t.u64().name("weekly_income"),
  monthlyIncome: __t.u64().name("monthly_income"),
  dayKey: __t.string().name("day_key"),
  weekKey: __t.string().name("week_key"),
  monthKey: __t.string().name("month_key"),
  updatedAt: __t.timestamp().name("updated_at"),
  playerLevel: __t.u32().name("player_level"),
});
