// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  username: __t.string(),
  allianceTag: __t.string().name("alliance_tag"),
  allianceTagColor: __t.string().name("alliance_tag_color"),
  totalIncome: __t.u64().name("total_income"),
  income: __t.u64(),
  dailyIncome: __t.u64().name("daily_income"),
  weeklyIncome: __t.u64().name("weekly_income"),
  monthlyIncome: __t.u64().name("monthly_income"),
  updatedAt: __t.timestamp().name("updated_at"),
  playerLevel: __t.u32().name("player_level"),
  dailyRank: __t.u32().name("daily_rank"),
  weeklyRank: __t.u32().name("weekly_rank"),
  monthlyRank: __t.u32().name("monthly_rank"),
  allTimeRank: __t.u32().name("all_time_rank"),
});
