// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  analyticsKey: __t.string().primaryKey().name("analytics_key"),
  dayKey: __t.string().name("day_key"),
  itemKey: __t.string().name("item_key"),
  itemLabel: __t.string().name("item_label"),
  itemKind: __t.string().name("item_kind"),
  npcBoughtQuantity: __t.u64().name("npc_bought_quantity"),
  npcSoldQuantity: __t.u64().name("npc_sold_quantity"),
  marketPriceGold: __t.u64().name("market_price_gold"),
  npcStock: __t.u64().name("npc_stock"),
  targetStock: __t.u64().name("target_stock"),
  demandScore: __t.u64().name("demand_score"),
  supplyScore: __t.u64().name("supply_score"),
  updatedAt: __t.timestamp().name("updated_at"),
  priceScale: __t.u32().name("price_scale"),
});
