// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  snapshotKey: __t.string().primaryKey().name("snapshot_key"),
  hourKey: __t.string().name("hour_key"),
  itemKey: __t.string().name("item_key"),
  itemLabel: __t.string().name("item_label"),
  itemKind: __t.string().name("item_kind"),
  marketPriceGold: __t.u64().name("market_price_gold"),
  npcBuyPriceGold: __t.u64().name("npc_buy_price_gold"),
  npcSellPriceGold: __t.u64().name("npc_sell_price_gold"),
  npcNeed: __t.u64().name("npc_need"),
  npcStock: __t.u64().name("npc_stock"),
  updatedAt: __t.timestamp().name("updated_at"),
  priceScale: __t.u32().name("price_scale"),
  marketId: __t.string().name("market_id"),
});
