// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  itemKey: __t.string().primaryKey().name("item_key"),
  itemLabel: __t.string().name("item_label"),
  itemKind: __t.string().name("item_kind"),
  defaultBasePriceGold: __t.u64().name("default_base_price_gold"),
  basePriceGold: __t.u64().name("base_price_gold"),
  updatedAt: __t.timestamp().name("updated_at"),
  targetStock: __t.u64().name("target_stock"),
  volatilityBps: __t.u64().name("volatility_bps"),
  enabled: __t.bool(),
});
