// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  itemKey: __t.string().primaryKey().name("item_key"),
  itemLabel: __t.string().name("item_label"),
  itemKind: __t.string().name("item_kind"),
  basePriceGold: __t.u64().name("base_price_gold"),
  marketPriceGold: __t.u64().name("market_price_gold"),
  npcBuyPriceGold: __t.u64().name("npc_buy_price_gold"),
  npcSellPriceGold: __t.u64().name("npc_sell_price_gold"),
  npcStock: __t.u64().name("npc_stock"),
  targetStock: __t.u64().name("target_stock"),
  demandScore: __t.u64().name("demand_score"),
  supplyScore: __t.u64().name("supply_score"),
  updatedAt: __t.timestamp().name("updated_at"),
  lastTickAt: __t.timestamp().name("last_tick_at"),
  npcNeed: __t.u64().name("npc_need"),
  targetNeed: __t.u64().name("target_need"),
  maxNeed: __t.u64().name("max_need"),
  priceScale: __t.u32().name("price_scale"),
  marketId: __t.string().name("market_id"),
});
