// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  royaltyId: __t.uuid().primaryKey().name("royalty_id"),
  recipientIdentity: __t.identity().name("recipient_identity"),
  sourceSellerIdentity: __t.identity().name("source_seller_identity"),
  sourceSellerUsername: __t.string().name("source_seller_username"),
  potionKey: __t.string().name("potion_key"),
  potionLabel: __t.string().name("potion_label"),
  royaltyGold: __t.u64().name("royalty_gold"),
  sourceIncomeGold: __t.u64().name("source_income_gold"),
  awardedAt: __t.timestamp().name("awarded_at"),
  goldScale: __t.u32().name("gold_scale"),
  marketId: __t.string().name("market_id"),
});
