// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  memberIdentity: __t.identity().primaryKey().name("member_identity"),
  allianceId: __t.uuid().name("alliance_id"),
  username: __t.string(),
  playerLevel: __t.u32().name("player_level"),
  role: __t.string(),
  joinedAt: __t.timestamp().name("joined_at"),
  memberUpdatedAt: __t.timestamp().name("member_updated_at"),
  totalContribution: __t.u64().name("total_contribution"),
  dailyContribution: __t.u64().name("daily_contribution"),
  memberDayKey: __t.string().name("member_day_key"),
  name: __t.string(),
  normalizedName: __t.string().name("normalized_name"),
  tag: __t.string(),
  tagColor: __t.string().name("tag_color"),
  description: __t.string(),
  notice: __t.string(),
  joinMode: __t.string().name("join_mode"),
  leaderIdentity: __t.identity().name("leader_identity"),
  memberCount: __t.u32().name("member_count"),
  totalIncome: __t.u64().name("total_income"),
  seasonIncome: __t.u64().name("season_income"),
  createdAt: __t.timestamp().name("created_at"),
  allianceUpdatedAt: __t.timestamp().name("alliance_updated_at"),
  seasonKey: __t.string().name("season_key"),
  dayKey: __t.string().name("day_key"),
  dailyIncome: __t.u64().name("daily_income"),
  monthlyIncome: __t.u64().name("monthly_income"),
  monthKey: __t.string().name("month_key"),
});
