// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  listingKey: __t.string().primaryKey().name("listing_key"),
  sellerIdentity: __t.identity().name("seller_identity"),
  username: __t.string(),
  slotNumber: __t.u8().name("slot_number"),
  itemKey: __t.string().name("item_key"),
  itemLabel: __t.string().name("item_label"),
  itemKind: __t.string().name("item_kind"),
  quantity: __t.u32(),
  priceGold: __t.u64().name("price_gold"),
  updatedAt: __t.timestamp().name("updated_at"),
  priceScale: __t.u32().name("price_scale"),
  marketId: __t.string().name("market_id"),
});
