// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  rewardKey: __t.string().primaryKey().name("reward_key"),
  recipientIdentity: __t.identity().name("recipient_identity"),
  allianceId: __t.uuid().name("alliance_id"),
  allianceName: __t.string().name("alliance_name"),
  questId: __t.string().name("quest_id"),
  questLabel: __t.string().name("quest_label"),
  dayKey: __t.string().name("day_key"),
  crystalReward: __t.u32().name("crystal_reward"),
  claimedAt: __t.timestamp().name("claimed_at"),
});
