// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  requestKey: __t.string().primaryKey().name("request_key"),
  playerIdentity: __t.identity().name("player_identity"),
  username: __t.string(),
  character: __t.string(),
  frame: __t.string(),
  playerLevel: __t.u32().name("player_level"),
  connected: __t.bool(),
  lastSeenAt: __t.timestamp().name("last_seen_at"),
  createdAt: __t.timestamp().name("created_at"),
  allianceTag: __t.string().name("alliance_tag"),
  allianceTagColor: __t.string().name("alliance_tag_color"),
});
