// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  mailKey: __t.string().primaryKey().name("mail_key"),
  recipientIdentity: __t.identity().name("recipient_identity"),
  sourceType: __t.string().name("source_type"),
  sourceKey: __t.string().name("source_key"),
  senderLabel: __t.string().name("sender_label"),
  title: __t.string(),
  body: __t.string(),
  rewardText: __t.string().name("reward_text"),
  coinReward: __t.u64().name("coin_reward"),
  crystalReward: __t.u32().name("crystal_reward"),
  rubyReward: __t.u32().name("ruby_reward"),
  emeraldReward: __t.u32().name("emerald_reward"),
  itemRewardsJson: __t.string().name("item_rewards_json"),
  createdAt: __t.timestamp().name("created_at"),
  read: __t.bool(),
  rewardCollected: __t.bool().name("reward_collected"),
});
