// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  messageId: __t.uuid().primaryKey().name("message_id"),
  allianceId: __t.uuid().name("alliance_id"),
  allianceTag: __t.string().name("alliance_tag"),
  senderIdentity: __t.identity().name("sender_identity"),
  username: __t.string(),
  playerLevel: __t.u32().name("player_level"),
  body: __t.string(),
  sentAt: __t.timestamp().name("sent_at"),
});
