// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  tradeId: __t.uuid().primaryKey().name("trade_id"),
  buyerIdentity: __t.identity().name("buyer_identity"),
  buyerUsername: __t.string().name("buyer_username"),
  sellerIdentity: __t.identity().name("seller_identity"),
  sellerUsername: __t.string().name("seller_username"),
  itemKey: __t.string().name("item_key"),
  itemLabel: __t.string().name("item_label"),
  itemKind: __t.string().name("item_kind"),
  quantity: __t.u32(),
  priceGold: __t.u64().name("price_gold"),
  totalPriceGold: __t.u64().name("total_price_gold"),
  tradedAt: __t.timestamp().name("traded_at"),
});
