// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  potionKey: __t.string().primaryKey().name("potion_key"),
  potionLabel: __t.string().name("potion_label"),
  discoveredByIdentity: __t.identity().name("discovered_by_identity"),
  username: __t.string(),
  discoveredAt: __t.timestamp().name("discovered_at"),
  royaltyGold: __t.u64().name("royalty_gold"),
  royaltyGoldScale: __t.u32().name("royalty_gold_scale"),
});
