// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  researchId: __t.string().primaryKey().name("research_id"),
  label: __t.string(),
  groupId: __t.string().name("group_id"),
  defaultCostGold: __t.u64().name("default_cost_gold"),
  costGold: __t.u64().name("cost_gold"),
  enabled: __t.bool(),
  updatedAt: __t.timestamp().name("updated_at"),
  durationSeconds: __t.u64().name("duration_seconds"),
});
