// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  applicationKey: __t.string().primaryKey().name("application_key"),
  allianceId: __t.uuid().name("alliance_id"),
  applicantIdentity: __t.identity().name("applicant_identity"),
  username: __t.string(),
  playerLevel: __t.u32().name("player_level"),
  createdAt: __t.timestamp().name("created_at"),
});
