// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  contributionKey: __t.string().primaryKey().name("contribution_key"),
  allianceId: __t.uuid().name("alliance_id"),
  dayKey: __t.string().name("day_key"),
  questId: __t.string().name("quest_id"),
  contributorIdentity: __t.identity().name("contributor_identity"),
  username: __t.string(),
  contribution: __t.u64(),
  updatedAt: __t.timestamp().name("updated_at"),
});
