// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  memberIdentity: __t.identity().primaryKey().name("member_identity"),
  allianceId: __t.uuid().name("alliance_id"),
  username: __t.string(),
  playerLevel: __t.u32().name("player_level"),
  role: __t.string(),
  joinedAt: __t.timestamp().name("joined_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  totalContribution: __t.u64().name("total_contribution"),
  dailyContribution: __t.u64().name("daily_contribution"),
  dayKey: __t.string().name("day_key"),
});
