// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  allianceId: __t.uuid().primaryKey().name("alliance_id"),
  name: __t.string(),
  normalizedName: __t.string().name("normalized_name"),
  tag: __t.string(),
  description: __t.string(),
  notice: __t.string(),
  joinMode: __t.string().name("join_mode"),
  leaderIdentity: __t.identity().name("leader_identity"),
  memberCount: __t.u32().name("member_count"),
  totalIncome: __t.u64().name("total_income"),
  seasonIncome: __t.u64().name("season_income"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  seasonKey: __t.string().name("season_key"),
  dayKey: __t.string().name("day_key"),
  dailyIncome: __t.u64().name("daily_income"),
  monthlyIncome: __t.u64().name("monthly_income"),
  monthKey: __t.string().name("month_key"),
  tagColor: __t.string().name("tag_color"),
});
