// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  questKey: __t.string().primaryKey().name("quest_key"),
  allianceId: __t.uuid().name("alliance_id"),
  dayKey: __t.string().name("day_key"),
  questId: __t.string().name("quest_id"),
  label: __t.string(),
  questType: __t.string().name("quest_type"),
  target: __t.u64(),
  progress: __t.u64(),
  minContribution: __t.u64().name("min_contribution"),
  crystalReward: __t.u32().name("crystal_reward"),
  updatedAt: __t.timestamp().name("updated_at"),
});
