// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Leaderboard = __t.object("Leaderboard", {
  identity: __t.identity(),
  username: __t.string(),
  totalIncome: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type Leaderboard = __Infer<typeof Leaderboard>;

export const NpcMarketPrice = __t.object("NpcMarketPrice", {
  itemKey: __t.string(),
  itemLabel: __t.string(),
  itemKind: __t.string(),
  basePriceGold: __t.u64(),
  marketPriceGold: __t.u64(),
  npcBuyPriceGold: __t.u64(),
  npcSellPriceGold: __t.u64(),
  npcStock: __t.u64(),
  targetStock: __t.u64(),
  demandScore: __t.u64(),
  supplyScore: __t.u64(),
  updatedAt: __t.timestamp(),
  lastTickAt: __t.timestamp(),
});
export type NpcMarketPrice = __Infer<typeof NpcMarketPrice>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  username: __t.string(),
  connected: __t.bool(),
  createdAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const PlayerShopListing = __t.object("PlayerShopListing", {
  listingKey: __t.string(),
  sellerIdentity: __t.identity(),
  username: __t.string(),
  slotNumber: __t.u8(),
  itemKey: __t.string(),
  itemLabel: __t.string(),
  itemKind: __t.string(),
  quantity: __t.u32(),
  priceGold: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type PlayerShopListing = __Infer<typeof PlayerShopListing>;

export const PlayerShopProceeds = __t.object("PlayerShopProceeds", {
  sellerIdentity: __t.identity(),
  gold: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type PlayerShopProceeds = __Infer<typeof PlayerShopProceeds>;

export const WorldChat = __t.object("WorldChat", {
  messageId: __t.uuid(),
  senderIdentity: __t.identity(),
  username: __t.string(),
  body: __t.string(),
  sentAt: __t.timestamp(),
});
export type WorldChat = __Infer<typeof WorldChat>;

