// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Leaderboard = __t.object("Leaderboard", {
  identity: __t.identity(),
  username: __t.string(),
  totalIncome: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type Leaderboard = __Infer<typeof Leaderboard>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  username: __t.string(),
  connected: __t.bool(),
  createdAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

