// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  contributionKey: __t.string().primaryKey().name("contribution_key"),
  identity: __t.identity(),
  periodKey: __t.string().name("period_key"),
  eventId: __t.string().name("event_id"),
  username: __t.string(),
  points: __t.u64(),
  updatedAt: __t.timestamp().name("updated_at"),
  playerLevel: __t.u32().name("player_level"),
});
